version: '3.7'

volumes:
  vol-wp-content:
  vol-wp-images:
  vol-wp-db:
  redis-data:

networks:
  frontend:
    external: true
  backend:
    driver: bridge

services:
  reverse-proxy:
    image: traefik:1.7-alpine
    restart: unless-stopped
    container_name: reverse-proxy
    networks:
      - frontend
      - backend
    command: --docker
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.frontend.rule=Host:web.com,www.web.com"
      - "traefik.docker.network=backend"
      - "traefik.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./traefik.toml:/traefik.toml
      - ./certs:/certs

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - backend
    container_name: redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - 'redis-data:/bitnami/redis/data'
    labels:
      - "traefik.enable=false"

 db:
    image: mariadb:10.4
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - vol-wp-db:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/zzz_my.cnf
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=db
    labels:
      - "traefik.enable=false"

  wordpress:
    depends_on:
      - db
    networks:
      - backend
    container_name: wordpress
    env_file:
      - .env
    build: ./
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - vol-wp-content:/var/www/wp-content
      - vol-wp-images:/usr/src/wordpress/images
    labels:
      - "traefik.backend=wordpress"
      - "traefik.frontend.rule=Host:web.com,www.web.com"
      - "traefik.docker.network=backend"
      - "traefik.frontend.protocol=https"
      - "traefik.enable=true"


