defaultEntryPoints = ["https","http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.http.redirect]
    regex = "^http:\\/\\/(www.)*(web\\.com)(.*)"
    replacement = "https://www.$2$3"
    permanent = true

  [entryPoints.https]
  address = ":443"
  compress = true

  [entryPoints.https.redirect]
    regex = "^https:\\/\\/(web.com)(.*)"
    replacement = "https://www.$1$2"
    permanent = true

    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
      ]
      [[entryPoints.https.tls.certificates]]
        certFile = "certs/traefik.crt"
        keyFile = "certs/traefik.key"
